name = "srvdetailin2"
main = ".open-next/worker.js"
compatibility_date = "2026-08-11"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[vars]
SUPABASE_URL = "https://kjbcgucumyszdflywdha.supabase.co"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
