import { Shield } from 'lucide-react';
import type { ServicePageData } from '@/data/types';

export const ceramicCoatingWarrington: ServicePageData = {
  slug: 'ceramic-coating',
  name: 'Ceramic Coating Warrington',
  seo: {
    title: 'Ceramic Coating Warrington | Long-Term Paint Protection | SRV Detailing',
    description:
      'Professional ceramic coating in Warrington. 2 to 7+ year paint protection against motorway fallout, road salt and Mersey Valley damp. Accredited application. Mobile service across WA1–WA5.',
    keywords: [
      'ceramic coating warrington',
      'car ceramic coating warrington',
      'ceramic paint protection warrington',
      'ceramic coating near me warrington',
      'paint protection warrington',
    ],
    canonical: 'https://www.srvdetailing.co.uk/warrington/car-detailing/ceramic-coating',
  },
  icon: Shield,
  breadcrumbs: [
    { label: 'Home', href: '/' },
    { label: 'Warrington', href: '/warrington' },
    { label: 'Car Detailing', href: '/warrington/car-detailing' },
    { label: 'Ceramic Coating', href: '/warrington/car-detailing/ceramic-coating' },
  ],
  heroTitle: 'Ceramic Coating in Warrington',
  heroDescription:
    "Long-lasting paint protection against Warrington's motorway fallout, road salt and damp Mersey Valley conditions. Professional application with 2 to 7+ year durability. We come to you anywhere across WA1–WA5.",
  contentSections: [
    {
      type: 'text',
      heading: 'What Is Ceramic Coating?',
      body: "Ceramic coating is a liquid polymer that chemically bonds with your vehicle's paintwork to create a semi-permanent protective layer. Unlike waxes that last weeks or sealants that last months, a professionally applied ceramic coating lasts 2 to 7+ years. It creates a hydrophobic surface that repels water, road grime and contaminants — delivering a deep, glossy finish that's dramatically easier to maintain.",
    },
    {
      type: 'list',
      heading: 'Why Warrington Cars Need Ceramic Coating',
      items: [
        "Hydrophobic barrier against Warrington's road spray and persistent Mersey Valley damp conditions",
        'Chemical resistance to the heavy road salt spread across the M6, M62 and A-road network each winter',
        'Defence against diesel particulates, tyre rubber and industrial fallout from the M6/M62 corridor',
        'Protection from iron contamination generated by Birchwood and Gemini business park traffic',
        'UV resistance for vehicles parked in open-air car parks at Warrington retail parks',
        'Dramatically easier washing — road grime slides off the coated surface rather than bonding to it',
      ],
    },
    {
      type: 'process',
      heading: 'Our Ceramic Coating Process',
      items: [
        'Full decontamination wash — snow foam pre-wash, two-bucket contact wash, iron fallout removal and clay bar',
        'Paint correction — machine polishing to remove swirl marks, scratches and oxidation before coating',
        'IPA wipe-down to strip all polishing oils and ensure a perfectly clean surface for chemical bonding',
        'Ceramic coating application — applied panel by panel in controlled conditions, levelled and buffed',
        'IR curing — we use infrared lamps to accelerate the initial cure for maximum coating hardness',
        'Final inspection under professional lighting and full aftercare walkthrough',
      ],
    },
    {
      type: 'text',
      heading: 'Ceramic Coating Packages',
      body: 'We offer three tiers of ceramic coating to suit different budgets and protection requirements. Entry-level packages (£300–£400) provide 3-year protection with excellent hydrophobic properties. Mid-range packages (£500–£700) deliver 3–4 year protection with superior chemical resistance. Premium packages (£800–£1,200+) offer 5–7+ years of maximum protection with the deepest gloss and hardest coating available.',
    },
  ],
  faqs: [
    {
      question: 'How long does ceramic coating last in Warrington conditions?',
      answer:
        "Ceramic coatings last between 3 and 7+ years depending on the package chosen. Warrington's heavy motorway exposure means proper maintenance is important — we provide full aftercare guidance and pH-neutral maintenance products to maximise longevity.",
    },
    {
      question: 'Is paint correction necessary before ceramic coating?',
      answer:
        'Yes. Ceramic coating locks in whatever is underneath — including swirl marks and scratches. We always correct the paint first so the coating seals a flawless finish. This is included in all our ceramic coating packages.',
    },
    {
      question: 'Can you apply ceramic coating at my home in Warrington?',
      answer:
        'Yes. Our mobile unit is equipped with professional lighting, IR curing lamps and a controlled environment setup. We can apply ceramic coatings on your driveway or in a covered space anywhere across Warrington.',
    },
    {
      question: 'How much does ceramic coating cost in Warrington?',
      answer:
        'Packages start from £300 for entry-level 3-year protection, rising to £800–£1,200+ for premium 5–7+ year coatings. Final price depends on vehicle size and paint condition. Contact us for an exact quote.',
    },
    {
      question: 'How do I maintain a ceramic coating?',
      answer:
        'Wash with a pH-neutral shampoo every 1–2 weeks and apply a ceramic boost spray every 3–6 months. Avoid automated car washes entirely. We supply full aftercare products and guidance with every coating.',
    },
  ],
  relatedLinks: [
    { label: 'Paint Correction Warrington', href: '/warrington/car-detailing/paint-correction', description: 'Remove swirl marks before coating' },
    { label: 'Exterior Detailing Warrington', href: '/warrington/car-detailing/exterior-detailing', description: 'Full exterior decontamination' },
    { label: 'Car Detailing Warrington', href: '/warrington/car-detailing', description: 'All detailing services' },
    { label: 'Ceramic Coating Prices', href: '/pricing/car-detailing', description: 'View all pricing' },
    { label: 'What Is Ceramic Coating?', href: '/guides/what-is-ceramic-coating', description: 'Complete guide' },
  ],
  schemaPrice: '300',
};
